services:
  db:
    image: postgres:17.4
    platform: linux/amd64
    environment:
      POSTGRES_DB: klub_fitness
      POSTGRES_USER: fitnesiara
      POSTGRES_PASSWORD: klubfitness
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: klubfitnessapp:latest
    platform: linux/amd64
    environment:
      SPRING_APPLICATION_NAME: KlubFitness
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/klub_fitness
      SPRING_DATASOURCE_USERNAME: fitnesiara
      SPRING_DATASOURCE_PASSWORD: klubfitness
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  db-data:
